apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  creationTimestamp: "2023-04-06T06:46:27Z"
  generation: 4
  labels:
    app.kubernetes.io/part-of: log4j
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
  name: log4j
  namespace: dev-space
  resourceVersion: "1301350890"
  uid: 8ae3ffde-5c00-4dac-9bcb-d9bb78fee4d1
spec:
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
  source:
    git:
      ref:
        branch: main
      url: https://github.com/tsalm-vmware/spring-boot-log4j-vulnerability-sample.git
